version: '2'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    links:
      - db
    command: rails s -p 3000 -b 0.0.0.0
